---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
  name: v1alpha1.controlplane.cloud.antrea.io
spec:
  group: controlplane.cloud.antrea.io
  groupPriorityMinimum: 100
  service:
    name: cloud-service
    namespace: system
  version: v1alpha1
  versionPriority: 100
