apiVersion: v1
kind: Service
metadata:
  name: cloud-controller-webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: cloud-controller
