apiVersion: crd.cloud.antrea.io/v1alpha1
kind: CloudEntitySelector
metadata:
  name: cloudentityselector-sample01
  namespace: sample-ns
spec:
  # Add fields here
  accountName: cloudprovideraccount-sample
  vmSelector:
    vmMatches:
      - vpcMatch:
          matchID: ""
