# Add Azure Account and Onboard VNET
apiVersion: crd.cloud.antrea.io/v1alpha1
kind: CloudProviderAccount
metadata:
  name: cloudprovideraccount-sample
  namespace: sample-ns
spec:
  azureConfig:
    subscriptionId: "<REPLACE_ME>"
    clientId: "<REPLACE_ME>"
    tenantId: "<REPLACE_ME>"
    clientKey: "<REPLACE_ME>"
    region: "<REPLACE_ME>"
---
apiVersion: crd.cloud.antrea.io/v1alpha1
kind: CloudEntitySelector
metadata:
  name: cloudentityselector-sample
  namespace: sample-ns
spec:
  accountName: cloudprovideraccount-sample
  vmSelector:
    - vpcMatch:
        matchID: "<VNET_ID>"
