# Add AWS Account and Onboard VPC
apiVersion: crd.cloud.antrea.io/v1alpha1
kind: CloudProviderAccount
metadata:
  name: cloudprovideraccount-sample
  namespace: sample-ns
spec:
  awsConfig:
    accountID: "<REPLACE_ME>"
    accessKeyId: "<REPLACE_ME>"
    accessKeySecret: "<REPLACE_ME>"
    region: "<REPLACE_ME>"
---
apiVersion: crd.cloud.antrea.io/v1alpha1
kind: CloudEntitySelector
metadata:
  name: cloudentityselector-sample
  namespace: sample-ns
spec:
  accountName: cloudprovideraccount-sample
  vmSelector:
    vmMatches:
      - vpcMatch:
          matchID: "<VPC_ID>"
