apiVersion: crd.cloud.antrea.io/v1alpha1
kind: CloudEntitySelector
metadata:
  name: cloudentityselector-sample01
  namespace: sample-ns
spec:
  accountName: cloudprovideraccount-sample
  vmSelector:
      - vpcMatch:
          matchID: "<VPC_ID>"
