apiVersion: crd.antrea.io/v1alpha1
kind: ExternalEntity
metadata:
  name: externalentity-sample
spec:
  externalNode: cloud-controller
  endpoints:
    - ip: 1.1.1.1
      ports:
        - protocol: TCP
          port: 80
          name: http
        - protocol: TCP
          port: 443
          name: https
    - ip: 2.2.2.2
      ports:
        - protocol: TCP
          port: 80
          name: http
        - protocol: TCP
          port: 443
          name: https
