- defaults:
    name: global
    ghpr_auth: 414be665-2f4a-4e73-82f0-e2169abc6720
    testrepo_admin_list: ["liu4480"]
    testrepo_org_list: ["liu4480"]
    testrepo_white_list: []
    org_repo: "liu4480/testrepo"
