---
- name: Add an APT Signing Key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get Ubuntu Release
  shell: lsb_release -cs
  register: lsb_release_result
  changed_when: False

- name: Add APT Repository for Stable Version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release_result.stdout }} stable
    state: present

- name: Install Docker and Dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    force_apt_get: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Setup docker daemon
  shell:
    cmd: |
      cat > /etc/docker/daemon.json<<EOF
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
      EOF

- name: Create docker service config dir if missing
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Setup docker proxy
  shell:
    cmd: |
      cat > /etc/systemd/system/docker.service.d/proxy.conf<<EOF
      [Service]
      Environment="NO_PROXY=localhost,127.0.0.1,::1,*.artifactory.eng.vmware.com,harbor-repo.vmware.com,projects.registry.vmware.com"
      EOF

- name: Reload service docker
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted

- name: Add jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Allow ubuntu user to Manage Docker
  tags: docker
  user:
    name: ubuntu
    groups: docker
    append: yes

# Install docker-py so that docker images can be pulled
- pip:
    name: docker-py

#- name: Log into docker hub
#  docker_login:
#    registry: nsx-ujo-docker-local.artifactory.eng.vmware.com
#    username: "{{ ANTREA_DOCKER_USERNAME }}"
#    password: "{{ ANTREA_DOCKER_PWD }}"
#    reauthorize: yes

- name: Pull httpbin Image from dockerhub and Tag
  docker_image:
    name: kennethreitz/httpbin:latest
    repository: httpbin:latest
    pull: yes

- name: Pull alpine-curl Image from dockerhub and Tag
  docker_image:
    name: byrnedo/alpine-curl:latest
    repository: alpine-curl:latest
    pull: yes

- name: Pull cert-manager-controller Image from quay.io and Tag
  docker_image:
    name: quay.io/jetstack/cert-manager-controller:v1.8.2
    repository: cert-manager-controller:v1.8.2
    pull: yes

- name: Pull cert-manager-controller Image from quay.io and Tag
  docker_image:
    name: quay.io/jetstack/cert-manager-controller:v1.8.2
    repository: cert-manager-controller:v1.8.2
    pull: yes

- name: Pull cert-manager-webhook Image from quay.io and Tag
  docker_image:
    name: quay.io/jetstack/cert-manager-webhook:v1.8.2
    repository: cert-manager-webhook:v1.8.2
    pull: yes

- name: Pull cert-manager-cainjector Image from quay.io and Tag
  docker_image:
    name: quay.io/jetstack/cert-manager-cainjector:v1.8.2
    repository: cert-manager-cainjector:v1.8.2
    pull: yes

- name: Pull antrea Image from internal repository and Tag
  docker_image:
    name: projects.registry.vmware.com/antrea/antrea-ubuntu:v1.7.0
    repository: antrea-ubuntu:v1.7.0
    pull: yes