name: Build and push latest image if needed

on:
  pull_request:
    branches:
      - master
      - release-*
      - feature/*
  push:
    branches:
      - master
      - release-*
      - feature/*

jobs:
  check-changes:
    name: Check whether tests need to be run based on diff
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: antrea-io/has-changes@v2
        id: check_diff
        with:
          paths-ignore: docs/*
    outputs:
      has_changes: ${{ steps.check_diff.outputs.has_changes }}

  build:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has_changes == 'yes' || github.event_name == 'push' }}
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          
      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
          
      - name: Install go modules
        run: |
          TMP_DIR=$(mktemp -d) && cd $TMP_DIR
          GO111MODULE=on go get github.com/golang/mock/mockgen@v1.6.0
          GO111MODULE=on go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.8.0
          GO111MODULE=on go get sigs.k8s.io/kustomize/kustomize/v3@v3.8.7
          GO111MODULE=on go get github.com/mgechev/revive@v1.0.9
          cd - && rm -rf $TMP_DIR
          go mod download  

      - name: Build Antrea Cloud
        run: |
          make build-bin
          make manifests
          git diff
          ci/check-gen.sh

