name: Build and push latest image if needed

on:
  pull_request:
    branches:
      - master
      - release-*
      - feature/*
  push:
    branches:
      - master
      - release-*
      - feature/*

jobs:
  check-changes:
    name: Check whether tests need to be run based on diff
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: antrea-io/has-changes@v2
      id: check_diff
      with:
        paths-ignore: docs/*
    outputs:
      has_changes: ${{ steps.check_diff.outputs.has_changes }}

  build:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has_changes == 'yes' || github.event_name == 'push' }}
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build Antrea Cloud Docker image without pushing to registry
      if: ${{github.event_name != 'push' || github.ref != 'refs/heads/master' }}
      run: |
        docker pull rahulj2021/builder:latest
	docker tag rahulj2021/builder:latest antrea-cloud/builder:latest
        make

    - name: Build and push Antrea Cloud Docker image to registry
      if: ${{github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        docker pull rahulj2021/builder:latest
	docker tag rahulj2021/builder:latest antrea-cloud/builder:latest
        make
	docker tag antrea/antrea-cloud:latest rahulj2021/antrea-cloud:latest
        docker push rahulj2021/antrea-cloud:latest
