name: TestEKS
on:
  pull_request:
    branches:
      - master
      - release-*
      - feature/*
  push:
    branches:
      - master
      - release-*
      - feature/*

  workflow_dispatch:

env:
  KIND_VERSION: v0.12.0
  KUBECTL_VERSION: v1.24.1
  TERRAFORM_VERSION: 1.2.2

jobs:
  check-changes:
    name: Check whether tests need to be run based on diff
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: antrea-io/has-changes@v2
        id: check_diff
        with:
          paths-ignore: docs/*
    outputs:
      has_changes: ${{ steps.check_diff.outputs.has_changes }}

  test-integration-eks:
    name: Integration tests on a EKS Cluster
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has_changes == 'yes' }}
    runs-on: [ubuntu-latest]
    steps:
          
      - uses: actions/checkout@v3
      - name: Build Nephe Docker image
        run: |
          # make build
         
      - name: Create EKS cluster
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_access_key_secret: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          TF_VAR_aws_key_pair_name: ${{ secrets.AWS_KEY_PAIR_NAME }}
          
        run: |
          mkdir $HOME/.aws
          echo "[default]" > $HOME/.aws/credentials
          echo "aws_access_key_id = $TF_VAR_aws_access_key_id" >> $HOME/.aws/credentials
          echo "aws_secret_access_key = $TF_VAR_aws_access_key_secret" >> $HOME/.aws/credentials
          
          cat $HOME/.aws/credentials
          echo "Rahul Jain" > $HOME/.aws/file1
          
      - name: Tar log files
        run: tar -czf log.tar.gz  -C $HOME/.aws . 

      - name: Upload test log
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-azure.tar.gz
          path: log.tar.gz
          retention-days: 1
