name: Go
on:
  pull_request:
    branches:
    - master
    - release-*
    - feature/*
  push:
    branches:
    - master
    - release-*
    - feature/*

env:
  go-cache-name: go

jobs:
  check-changes:
    name: Check whether tests need to be run based on diff
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: antrea-io/has-changes@v2
      id: check_diff
      with:
        paths-ignore: docs/*
    outputs:
      has_changes: ${{ steps.check_diff.outputs.has_changes }}

  test-unit:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has_changes == 'yes' }}
    name: Unit test
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub and download builder image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker pull rahulj2021/builder:latest
          docker tag rahulj2021/builder:latest antrea-cloud/builder:latest
          
      - name: Run unit tests
        run: make unit-test
