name: Kind
on:
  pull_request:
    branches:
      - master
      - release-*
      - feature/*
  push:
    branches:
      - master
      - release-*
      - feature/*
      
env:
  KIND_VERSION: v0.12.0
  KUBECTL_VERSION: v1.24.1
  TERRAFORM_VERSION: 0.13.5
    
jobs:
  check-changes:
    name: Check whether tests need to be run based on diff
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: antrea-io/has-changes@v2
        id: check_diff
        with:
          paths-ignore: docs/*
    outputs:
      has_changes: ${{ steps.check_diff.outputs.has_changes }}
      
  test-integration:
    name: Integration tests on a Kind cluster on Linux
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has_changes == 'yes' }}
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
      - name: Install Prerequisites
        run: |
          curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-$(uname)-amd64
          chmod +x ./kind
          mv ./kind /usr/local/bin/kind
          curl -LO https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
          chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
          curl -Lo ./terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip ./terraform.zip
          chmod +x ./terraform && mv ./terraform /usr/local/bin/terraform
                    
      - name: Build Antrea Cloud Image
        run: |
          docker pull rahulj2021/builder:latest
          docker tag rahulj2021/builder:latest antrea-cloud/builder:latest
          make
          
      - name: Pull Docker Images to be used in the tests
        run: |
          docker pull kennethreitz/httpbin
          docker pull byrnedo/alpine-curl
          docker pull quay.io/jetstack/cert-manager-controller:v1.8.2
          docker pull quay.io/jetstack/cert-manager-webhook:v1.8.2
          docker pull quay.io/jetstack/cert-manager-cainjector:v1.8.2
          docker pull projects.registry.vmware.com/antrea/antrea-ubuntu:v1.7.0
        
      - name: Create kind cluster
        run: |
          hack/install-cloud-tools.sh
          ci/kind/kind-setup.sh create kind

      - name: Run integration test
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_access_key_secret: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          TF_VAR_aws_key_pair_name: ${{ secrets.AWS_KEY_PAIR_NAME }}
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
          TF_VAR_owner: "ANTREACLOUD-CI"
        run: |
          hack/install-cloud-tools.sh
          mkdir log
          eval $(ssh-agent -s)
          echo "${SSH_KEY}" | tr -d '\r' | ssh-add -
          ssh-add  -l
          ci/bin/integration.test -ginkgo.v -ginkgo.focus=".*Core-test.*" -kubeconfig=$HOME/.kube/config -cloud-provider=AWS -support-bundle-dir=$(pwd)/log
          
      - name: Tar log files
        if: ${{ failure() }}
        run: tar -czf log.tar.gz log
        
      - name: Upload test log
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: integration-test.tar.gz
          path: log.tar.gz
          retention-days: 2
